# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daniel Kliewer
email: daniel.kliewer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Daniel Kliewer is a writer, researcher, and software developer. Explore insights on machine learning, 
  large language models, and software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielkliewer.com" # the base hostname & protocol for your site

twitter_username: kliewer_daniel
github_username:  kliewerdaniel

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  stories:
    output: true
    permalink: /stories/:path/

# Default layouts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-redesign"
  -
    scope:
      path: ""
      type: "stories"
    values:
      layout: "story"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Exclude problematic symlink files
  - static/input_images/B01N78T9F901_SCLZZZZZZZ_SX500_.jpg
  - static/input_images/B0BHLH14NQ01_SCLZZZZZZZ_SX500_.jpg
  - static/input_images/B0BW23BXYN01S001LXXXXXXX.jpg
  - static/input_images/books-003.JPG
  - static/input_images/books-005.JPG
  - static/input_images/books-007.JPG
  - static/input_images/books-013.JPG
  - static/input_images/books-015.JPG
  - static/input_images/books
  # Exclude additional dangling symlinks found in build logs
  - static/input_images/130188528_3781238605303881_7510459135709865265_n.jpg
  - static/input_images/144327630_3930950650332675_7163600755928566265_n.jpg
  - static/input_images/161777802_4047093135385092_472397087862373077_n.jpg
  - static/input_images/20221010_111253.jpg
  - static/input_images/20221010_145455.jpg
  - static/input_images/20221011_005157.jpg
  - static/input_images/20221012_105602.jpg
  - static/input_images/20221012_145451.jpg
  - static/input_images/20221013_125636.jpg
  - static/input_images/20221013_133924.jpg
  - static/input_images/20221013_134808.jpg
  - static/input_images/20221013_134815.jpg
  - static/input_images/20221013_140515.jpg
  - static/input_images/20221013_140630.jpg
  - static/input_images/20221013_140920.jpg
  - static/input_images/20221013_144240.jpg
  - static/input_images/20221013_144257.jpg
  - static/input_images/20221013_144305.jpg
  - static/input_images/20221013_170405.jpg
  - static/input_images/20221013_172115.jpg
  - static/input_images/20221013_174915.jpg
  - static/input_images/20221014_111722.jpg
  - static/input_images/20221014_124553.jpg
  - static/input_images/20221014_134512.jpg
  - static/input_images/20221014_153920.jpg
  - static/input_images/20221112_132825.jpg
  - static/input_images/20221113_153653.jpg
  - static/input_images/20221113_161248.jpg
  - static/input_images/20221113_161512.jpg
  - static/input_images/20221113_161526.jpg
  - static/input_images/20221113_161531.jpg
  - static/input_images/20221113_161540.jpg
  - static/input_images/20221113_161556.jpg
  - static/input_images/20221113_162250.jpg
  - static/input_images/20221113_162309.jpg
  - static/input_images/289641143_5461602423934149_1613512193125880228_n.jpg
  - static/input_images/314598570_5848149695279418_2663164436116368473_n.jpg
  - static/input_images/319815256_5961632573931129_6407827479216061436_.jpg
  - static/input_images/326218428_5882108565159414_5579593452106029515_n.jpg
  - static/input_images/38524618_2014124792015280_5352241592616878080_n.jpg
  - static/input_images/463314582_8751461421614883_6093502764820900015_n.jpg
  - static/input_images/463430190_8751461418281550_7714871349040429364_n.jpg
  - static/input_images/463437008_8751402828287409_6880135836708144342_n.jpg
  - static/input_images/463751864_8751403184954040_8729498268726413009_n.jpg
  - static/input_images/463784634_8751402834954075_5802434536383396028_n.jpg
  - static/input_images/463893960_8751402418287450_1246655841173803972_n.jpg
  - static/input_images/474775887_490715300428480_2081408431757738514_n.jpg
  - static/input_images/475838291_1316583769763327_611859964883411367_n.jpg
  - static/input_images/476485484_1684131429201363_7550930141077594240_n.jpg
  - static/input_images/476485520_618748147579301_2628358660310613573_n.jpg
  - static/input_images/476485893_1141800154331157_7662562200996339651_n.jpg
  - static/input_images/476902298_2026199734459132_8101314172205332991_n.jpg
  - static/input_images/477085949_1376430796875724_8916528934155297778_n.jpg
  - static/input_images/477493740_596522203209143_8128024935578485345_n.jpg
  - static/input_images/69941916-CF12-4AAE-8ABE-86BED96E8795.jpg
  - static/input_images/77082571-3717-4590-9131-5212AB1ACCAA.jpg
  - static/input_images/B01N78T9F9.01._SCLZZZZZZZ_SX500_.jpg
  - static/input_images/B0BHLH14NQ.01._SCLZZZZZZZ_SX500_.jpg
  - static/input_images/B0BW23BXYN.01.S001.LXXXXXXX.jpg
  - static/input_images/B2B11E10-05AD-4951-ADE3-917B92D36250.jpg
  - static/input_images/B9B57FFB-2251-44C5-8215-3DDD17162E1F.jpg
  - static/input_images/bridge.jpg
  - static/input_images/C8C6DEF8-4239-4B16-ADF3-4EAF62D4795A.jpg
  - static/input_images/captain.jpg
