# Site settings
title: Daniel Kliewer
email: daniel.kliewer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Daniel Kliewer is a writer, researcher, and software developer. Explore insights on machine learning, 
  large language models, and software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danielkliewer.com" # the base hostname & protocol for your site
permalink: pretty

# Social media
twitter_username: kliewer_daniel
github_username: kliewerdaniel

# Logo configuration
logo:
  mobile: ""
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "Daniel Kliewer"
  desktop_height: "32px"
  desktop_width: "120px"

# Home page settings
home: 
  limit_services: 6

# Collections
collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  posts:
    output: true

# Default layouts
defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Sass settings
sass:
  style: compressed # possible values: nested expanded compact compressed

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
