[build]
  # Custom build command that copies image files before running Jekyll build
  command = """
    mkdir -p static/input_images
    cp -r -L input_images01/* static/input_images/ || true
    cp -r -L input_images02/* static/input_images/ || true
    cp -r -L input_images03/* static/input_images/ || true
    cp -r -L input_images04/* static/input_images/ || true
    jekyll build
  """
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-sitemap"
