[build]
  # Custom build command that copies image files before running Jekyll build
  command = """
    mkdir -p static/input_images
    # Copy image files from input_images directories
    cp -r input_images01/* static/input_images/ || true
    cp -r input_images02/* static/input_images/ || true
    cp -r input_images03/* static/input_images/ || true
    cp -r input_images04/* static/input_images/ || true
    
    # Create empty placeholder files for problematic symlinks
    touch static/input_images/B01N78T9F901_SCLZZZZZZZ_SX500_.jpg
    touch static/input_images/B0BHLH14NQ01_SCLZZZZZZZ_SX500_.jpg
    touch static/input_images/B0BW23BXYN01S001LXXXXXXX.jpg
    touch static/input_images/books-003.JPG
    touch static/input_images/books-005.JPG
    touch static/input_images/books-007.JPG
    touch static/input_images/books-013.JPG
    touch static/input_images/books-015.JPG
    touch static/input_images/books
    
    # Run Jekyll build
    jekyll build
  """
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-sitemap"
